In [1]:
import numpy as np
import pandas as pd
import random

# Getting data 

## For cross validation

In [2]:
df = pd.read_csv(r'C:\Users\caron\OneDrive - University of North Carolina at Chapel Hill\Honors Project\CSV Files\MRI Data.csv')
temp = pd.concat([df.loc[0:, ['SDx']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False)
temp = temp.dropna(how='any')
df1 = temp.loc[0:, ['SDx']]
df2 = temp.loc[0:, 'L_LatVent': 'R_insula_surfavg']
temp

SDx  L_LatVent  R_LatVent  L_thal  R_thal  L_caud  R_caud   L_put  \
0       0     3655.0     4525.0  7829.0  7568.0  3301.0  3694.0  4942.0   
1       0     4885.0     3312.0  7567.0  7578.0  3467.0  3494.0  5282.0   
2       0     6065.0     6765.0  7823.0  8228.0  4218.0  4092.0  5473.0   
3       0     6941.0     7537.0  8022.0  8030.0  3892.0  3789.0  5220.0   
4       0     7553.0     9478.0  8443.0  7831.0  4291.0  4400.0  6516.0   
...   ...        ...        ...     ...     ...     ...     ...     ...   
1906    3     8780.8    14023.7  6737.6  7091.1  3236.3  3047.6  5027.8   
1907    3     3161.4     2368.4  5762.7  8192.6  2595.9  3472.5  5162.9   
1908    3     3519.5     4556.5  6929.9  8318.8  4362.4  4277.4  6637.9   
1909    3     4635.8     6822.7  6094.0  5009.4  3833.5  3413.3  5915.8   
1910    3     4363.2     3547.3  6977.2  9058.3  4986.1  4951.9  6135.3   

       R_put   L_pal  ...  R_rostralanteriorcingulate_surfavg  \
0     5403.0  1627.0  ...                               714.0   
1     5255.0  1769.0  ...                               708.0   
2     5562.0  1876.0  ...                               882.0   
3     5510.0  1663.0  ...                               647.0   
4     6326.0  1915.0  ...                               802.0   
...      ...     ...  ...                                 ...   
1906  5760.0  1236.2  ...                              1053.0   
1907  5551.1  1523.6  ...                               726.0   
1908  6432.2  1740.8  ...                               661.0   
1909  5266.7  1231.4  ...                               676.0   
1910  5867.4  1556.2  ...                               796.0   

      R_rostralmiddlefrontal_surfavg  R_superiorfrontal_surfavg  \
0                             5887.0                     7100.0   
1                             4955.0                     6524.0   
2                             5703.0                     7052.0   
3                             5782.0                     7226.0   
4                             5965.0                     8310.0   
...                              ...                        ...   
1906                          6365.0                     7041.0   
1907                          5236.0                     6705.0   
1908                          5959.0                     7597.0   
1909                          4632.0                     5960.0   
1910                          6488.0                     7769.0   

      R_superiorparietal_surfavg  R_superiortemporal_surfavg  \
0                         5952.0                      3312.0   
1                         4878.0                      3875.0   
2                         5066.0                      3386.0   
3                         4691.0                      3478.0   
4                         5416.0                      4498.0   
...                          ...                         ...   
1906                      5813.0                      3648.0   
1907                      5839.0                      3528.0   
1908                      5603.0                      3539.0   
1909                      4005.0                      2792.0   
1910                      5821.0                      4121.0   

      R_supramarginal_surfavg  R_frontalpole_surfavg  R_temporalpole_surfavg  \
0                      3372.0                  236.0                   383.0   
1                      3943.0                  268.0                   409.0   
2                      4190.0                  189.0                   606.0   
3                      3986.0                  240.0                   468.0   
4                      4455.0                  284.0                   479.0   
...                       ...                    ...                     ...   
1906                   3681.0                  247.0                   585.0   
1907                   3674.0                  225.0                   413.0   
1908                   3981.0 

## Split data

In [3]:
temp2 = pd.concat([df.loc[0:, ['SDx']], df.loc[0:, 'L_LatVent': 'R_insula_surfavg']], axis=1, sort=False)
temp2['Index'] = pd.Series(np.array(range(0, 1911))) #for df_to_compare 
temp2 = temp2.dropna(how='any').sample(frac=1).reset_index(drop=True)  
train = temp2[:523]
test = temp2[523:]
df1_train = train.loc[0:, ['SDx']]
df2_train = train.loc[0:, 'L_LatVent': 'R_insula_surfavg']
df1_test = test.loc[0:, ['SDx']]
df2_test = test.loc[0:, 'L_LatVent': 'R_insula_surfavg']

In [4]:
df_to_compare = pd.concat([temp2.loc[0:, ['SDx']], temp2.loc[0:, 'Index']], axis=1, sort=False)
df_to_compare = df_to_compare[523:]
df_to_compare
# df_to_compare is the same as df1_test (SDx test values) but includes original
# index of full df for reference

SDx  Index
523     0      2
524     0   1142
525     0    806
526     3   1322
527     0    125
...   ...    ...
1040    3   1267
1041    3   1605
1042    0    387
1043    0     75
1044    0    457

[522 rows x 2 columns]

In [5]:
y = np.array(df1).ravel()
x = np.array(df2)
y_train = np.array(df1_train).ravel()
x_train = np.array(df2_train)
y_test = np.array(df1_test).ravel()
x_test = np.array(df2_test)

# MinMaxScaler

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
mri_scaler = MinMaxScaler()
mri_scaler2 = MinMaxScaler()

# LinearSVC

In [8]:
from sklearn.svm import LinearSVC

In [9]:
mri_LinearSVC = LinearSVC()

# SVC

In [10]:
from sklearn.svm import SVC

In [11]:
mri_SVC = SVC()

# LinearSVC Pipeline

In [12]:
from sklearn.pipeline import Pipeline

In [13]:
mri_svm = Pipeline([('scaler', mri_scaler), ('svc', mri_LinearSVC)])

In [14]:
mri_svm.set_params(scaler__copy=True, svc__C=.1)
## still not sure what copy does

Pipeline(memory=None,
         steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('svc',
                 LinearSVC(C=0.1, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='squared_hinge', max_iter=1000,
                           multi_class='ovr', penalty='l2', random_state=None,
                           tol=0.0001, verbose=0))],
         verbose=False)

In [15]:
mri_svm.fit(x_train, y_train)
mri_svm.score(x_test, y_test)
# what does fit_transform do?

0.9061302681992337

In [16]:
xxx = LinearSVC(C=.1)
xxx.fit(x_train, y_train)
xxx.score(x_test, y_test)
# without scaler, its almost always less accurate at
# C=.1 but more accurate at 10 and .01 where pipeline has
# huge variation. Most accurate with pipeline at .1

C:\Users\caron\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.8716475095785441

In [17]:
mri_predict = mri_svm.predict(x_test)
# predictions in numpy array
mri_predict

array([0, 0, 0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 3,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 3, 0, 0,
       3, 3, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 3, 0, 3, 3, 0, 0, 3, 0, 3, 3, 0, 0,
       3, 0, 0, 0, 0, 3, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 3, 3, 0, 0, 0, 3, 0, 0, 3, 0, 3, 3, 3, 0, 3, 3, 3, 0, 0, 0, 3,
       0, 3, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 0, 3, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3,
       3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
       0, 0, 3, 3, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 3,
       0, 3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
       0, 3, 0, 0, 0, 0, 3, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3,

In [18]:
SDx_df = pd.DataFrame(data=mri_predict, columns=["SDx"])
SDx_df

SDx
0      0
1      0
2      0
3      3
4      0
..   ...
517    3
518    3
519    0
520    0
521    0

[522 rows x 1 columns]

In [19]:
df_to_compare
## correct SDx w/ index from original df

SDx  Index
523     0      2
524     0   1142
525     0    806
526     3   1322
527     0    125
...   ...    ...
1040    3   1267
1041    3   1605
1042    0    387
1043    0     75
1044    0    457

[522 rows x 2 columns]

# SVC Pipeline

In [20]:
mri_svm2 = Pipeline([('scaler', mri_scaler2), ('svc', mri_SVC)])

In [21]:
mri_svm2.set_params(scaler__copy=True, svc__C=1.1, svc__gamma='scale', svc__kernel='rbf')

Pipeline(memory=None,
         steps=[('scaler', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('svc',
                 SVC(C=1.1, cache_size=200, class_weight=None, coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma='scale',
                     kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [22]:
mri_svm2.fit(x_train, y_train)
mri_svm2.score(x_test, y_test)
# what does fit_transform do?

0.896551724137931

In [23]:
xxx2 = SVC(C=1.1, gamma='scale', kernel='rbf')
xxx2.fit(x_train, y_train)
xxx2.score(x_test, y_test)
# without scaler

0.8103448275862069

# Cross Validation Linear

In [24]:
from sklearn.model_selection import cross_validate

In [25]:
mri_cv = cross_validate(mri_svm, x, y, cv=5, return_train_score=True)

In [26]:
mri_cv['test_score']

array([0.69047619, 0.75119617, 0.81818182, 0.94736842, 0.89903846])

In [27]:
mri_cv['train_score']

array([0.92095808, 0.95454545, 0.94258373, 0.91866029, 0.91875747])

# Cross Validation Non-Linear

In [28]:
mri_cv = cross_validate(mri_svm2, x, y, cv=5, return_train_score=True)

In [29]:
mri_cv['test_score']

array([0.75238095, 0.76555024, 0.82296651, 0.95215311, 0.93269231])

In [30]:
mri_cv['train_score']

array([0.92934132, 0.96052632, 0.95334928, 0.93779904, 0.94384707])

# Cross Validate Predict Linear

In [31]:
from sklearn.model_selection import cross_val_predict

In [32]:
mri_cvp = cross_val_predict(mri_svm, x, y, cv=5)

In [33]:
mri_cvp
# predictions in numpy array

array([0, 0, 0, ..., 3, 3, 3], dtype=int64)

In [34]:
SDx_df2 = pd.DataFrame(data=mri_cvp, columns=["SDx"])

In [35]:
SDx_df2
# predictions in pandas datafram

SDx
0       0
1       0
2       0
3       0
4       0
...   ...
1040    3
1041    3
1042    3
1043    3
1044    3

[1045 rows x 1 columns]